<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quote #{{ $quote->id }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 15px;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #2563EB;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        h2 {
            font-size: 20px;
            margin-top: 20px;
            margin-bottom: 10px;
            color: #2563EB;
        }
        .quote-info {
            margin-bottom: 20px;
        }
        .quote-info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .tasks {
            margin-bottom: 20px;
        }
        .deliverables {
            margin-bottom: 20px;
        }
        .total {
            font-weight: bold;
            text-align: right;
            font-size: 18px;
            margin-top: 20px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">Planify</div>
        <h1>Quote #{{ $quote->id }}</h1>
    </div>

    <div class="quote-info">
        <p><strong>Project Name:</strong> {{ $quote->project_name }}</p>
        <p><strong>Website Type:</strong> {{ $quote->website_type->name }}</p>
        <p><strong>Created:</strong> {{ $quote->created_at->format('F j, Y') }}</p>
        <p><strong>Industry:</strong> {{ $quote->industry }}</p>
    </div>

    <h2>Project Description</h2>
    <p>{{ $quote->project_description }}</p>

    @if($quote->business_goals)
    <h2>Business Goals</h2>
    <p>{{ $quote->business_goals }}</p>
    @endif

    <h2>Solution Overview</h2>
    <p>{{ $quote->solution_overview }}</p>

    <h2>Tasks & Timeline</h2>
    <div class="tasks">
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Hours</th>
                    <th>Rate</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($taskBreakdown as $task)
                <tr>
                    <td>{{ $task['name'] }}</td>
                    <td>{{ $task['hours'] }}</td>
                    <td>${{ number_format($quote->hourly_rate, 2) }}/hr</td>
                    <td>${{ number_format($task['hours'] * $quote->hourly_rate, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3"><strong>Total</strong></td>
                    <td><strong>${{ number_format($totalAmount, 2) }}</strong></td>
                </tr>
            </tfoot>
        </table>
    </div>

    <h2>Deliverables</h2>
    <div class="deliverables">
        <ul>
            @foreach($deliverables as $deliverable)
            <li><strong>{{ $deliverable['name'] }}</strong> - {{ $deliverable['description'] }}</li>
            @endforeach
        </ul>
    </div>

    @if($quote->selected_features && count($quote->selected_features) > 0)
    <h2>Selected Features</h2>
    <div class="features">
        <ul>
            @foreach($quote->selected_features as $feature)
            <li><strong>{{ $feature->name }}</strong> - {{ $feature->description }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    @if($quote->custom_features)
    <h2>Custom Features</h2>
    <div class="custom-features">
        <ul>
            @foreach($quote->custom_features as $feature)
            <li><strong>{{ $feature['name'] }}</strong> - {{ $feature['description'] }} ({{ $feature['hours'] }} hours)</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="footer">
        <p>This quote was generated by Planify on {{ $date }}</p>
        <p>Valid for 30 days from the date of creation.</p>
    </div>
</body>
</html>